<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class BlogPostSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $posts = [
            [
                'slug'              => 'flowmeter-industrial-guide',
                'title'             => 'راهنمای جامع انتخاب فلومتر صنعتی: الکترومغناطیسی، اولتراسونیک یا کوریولیس؟',
                'excerpt'           => 'بررسی تخصصی انواع فلومترهای صنعتی با مقایسه دقت، رنج اندازه‌گیری، سازگاری با سیالات مختلف و هزینه نگهداری.',
                'category'          => 'راهنمای خرید',
                'product_categories'=> '["flow-meters"]',
                'product_types'     => '["electromagnetic-flow","ultrasonic-flow"]',
                'author'            => 'مهندس محمدی',
                'read_time'         => '۸ دقیقه',
                'published_at'      => '2024-04-08',
            ],
            [
                'slug'              => 'gas-detector-atex-installation',
                'title'             => '۷ نکته حیاتی برای نصب و راه‌اندازی دتکتور گاز در محیط‌های ATEX',
                'excerpt'           => 'الزامات استاندارد IEC 60079 برای نصب دتکتورهای گاز در مناطق خطرناک Zone 0، 1 و 2.',
                'category'          => 'ایمنی صنعتی',
                'product_categories'=> '["gas-detectors"]',
                'product_types'     => '["multi-gas","toxic-detector"]',
                'author'            => 'مهندس رضایی',
                'read_time'         => '۱۲ دقیقه',
                'published_at'      => '2024-04-03',
            ],
            [
                'slug'              => 'plc-siemens-rockwell-schneider-comparison',
                'title'             => 'مقایسه کارشناسی PLC زیمنس S7-1500، راکول CompactLogix و اشنایدر M580',
                'excerpt'           => 'تحلیل جامع سه PLC محبوب بازار ایران از نظر سرعت پردازش، ظرفیت I/O و پروتکل‌های ارتباطی.',
                'category'          => 'مقاله تخصصی',
                'product_categories'=> '["plc-equipment"]',
                'product_types'     => '["plc-cpu","hmi-panel"]',
                'author'            => 'مهندس کریمی',
                'read_time'         => '۱۰ دقیقه',
                'published_at'      => '2024-03-29',
            ],
            [
                'slug'              => 'iiot-instrumentation-future',
                'title'             => 'اینترنت اشیاء صنعتی (IIoT) و آینده ابزار دقیق: از سنسور تا Cloud',
                'excerpt'           => 'بررسی نقش IIoT در تحول صنعت ابزار دقیق: از سنسورهای هوشمند WirelessHART تا پلتفرم‌های ابری.',
                'category'          => 'فناوری نوین',
                'product_categories'=> '["plc-equipment","flow-meters"]',
                'product_types'     => '["plc-cpu","mass-flow-controller"]',
                'author'            => 'مهندس احمدی',
                'read_time'         => '۶ دقیقه',
                'published_at'      => '2024-03-14',
            ],
            [
                'slug'              => 'industrial-automation-iran',
                'title'             => 'چالش‌ها و فرصت‌های اتوماسیون صنعتی در ایران: نگاهی به آینده',
                'excerpt'           => 'تحلیل وضعیت فعلی بازار اتوماسیون صنعتی ایران و فرصت‌های رشد در صنایع نفت و گاز و پتروشیمی.',
                'category'          => 'تحلیل بازار',
                'product_categories'=> '["plc-equipment","gas-detectors"]',
                'product_types'     => '["plc-cpu","multi-gas"]',
                'author'            => 'دکتر رضایی',
                'read_time'         => '۸ دقیقه',
                'published_at'      => '2024-03-09',
            ],
            [
                'slug'              => 'calibration-importance-iso17025',
                'title'             => 'اهمیت کالیبراسیون دوره‌ای ابزار دقیق و تأثیر آن بر کیفیت تولید',
                'excerpt'           => 'چرا کالیبراسیون منظم تجهیزات اندازه‌گیری حیاتی است؟ بررسی استاندارد ISO 17025.',
                'category'          => 'کیفیت و استاندارد',
                'product_categories'=> '["gas-generators","flow-meters","gas-detectors"]',
                'product_types'     => '["nitrogen-gen","electromagnetic-flow","multi-gas"]',
                'author'            => 'مهندس موسوی',
                'read_time'         => '۷ دقیقه',
                'published_at'      => '2024-03-04',
            ],
            [
                'slug'              => 'lab-pumps-vacuum-peristaltic-guide',
                'title'             => 'راهنمای انتخاب پمپ خلأ و پریستالتیک آزمایشگاهی برای کاربردهای دقیق',
                'excerpt'           => 'مقایسه تخصصی پمپ‌های خلأ، پریستالتیک و دیافراگمی برای HPLC، نمونه‌برداری گاز و فرآیندهای آزمایشگاهی.',
                'category'          => 'راهنمای خرید',
                'product_categories'=> '["lab-pumps"]',
                'product_types'     => '["vacuum-pump","peristaltic-pump","diaphragm-pump"]',
                'author'            => 'مهندس نادری',
                'read_time'         => '۹ دقیقه',
                'published_at'      => '2024-03-24',
            ],
            [
                'slug'              => 'calibration-checklist-industrial',
                'title'             => 'چک‌لیست کامل کالیبراسیون دتکتورها و فلومترها در پروژه‌های صنعتی',
                'excerpt'           => 'یک راهنمای عملی برای برنامه‌ریزی کالیبراسیون، انتخاب گاز مرجع، مستندسازی و کاهش توقف خط تولید.',
                'category'          => 'کیفیت و استاندارد',
                'product_categories'=> '["calibration"]',
                'product_types'     => '["electromagnetic-flow","toxic-detector"]',
                'author'            => 'مهندس قاسمی',
                'read_time'         => '۱۱ دقیقه',
                'published_at'      => '2024-03-20',
            ],
            [
                'slug'              => 'gas-generators-overview',
                'title'             => 'راهنمای جامع ژنراتورهای گاز آزمایشگاهی و صنعتی: هیدروژن، نیتروژن و هوای خشک',
                'excerpt'           => 'بررسی کامل انواع ژنراتورهای گاز، اصول عملکرد، مقایسه فناوری‌های PSA، غشایی و الکترولیز و راهنمای انتخاب.',
                'category'          => 'راهنمای خرید',
                'product_categories'=> '["gas-generators"]',
                'product_types'     => '["hydrogen-gen","nitrogen-gen","dry-air-gen"]',
                'author'            => 'مهندس احمدی',
                'read_time'         => '۱۰ دقیقه',
                'published_at'      => '2024-04-19',
            ],
            [
                'slug'              => 'hydrogen-generator-pem-gc-icp',
                'title'             => 'ژنراتور هیدروژن آزمایشگاهی: اصول الکترولیز PEM و کاربرد در GC و ICP',
                'excerpt'           => 'بررسی عملکرد ژنراتورهای هیدروژن PEM برای گاز حامل کروماتوگرافی گازی و جایگزینی سیلندر هیدروژن.',
                'category'          => 'مقاله تخصصی',
                'product_categories'=> '["gas-generators"]',
                'product_types'     => '["hydrogen-gen"]',
                'author'            => 'مهندس کریمی',
                'read_time'         => '۹ دقیقه',
                'published_at'      => '2024-04-24',
            ],
            [
                'slug'              => 'nitrogen-generator-psa-membrane',
                'title'             => 'ژنراتور نیتروژن PSA و غشایی: مقایسه فنی و اقتصادی برای صنایع بسته‌بندی و آزمایشگاه',
                'excerpt'           => 'تحلیل دو فناوری اصلی تولید نیتروژن از هوا: جذب نوسانی فشار (PSA) و غشای فیبر توخالی.',
                'category'          => 'مقاله تخصصی',
                'product_categories'=> '["gas-generators"]',
                'product_types'     => '["nitrogen-gen"]',
                'author'            => 'مهندس محمدی',
                'read_time'         => '۱۱ دقیقه',
                'published_at'      => '2024-04-27',
            ],
            [
                'slug'              => 'dry-air-generator-fid-toc',
                'title'             => 'ژنراتور هوای خشک و هوای صفر: کاربرد در FID و TOC و الزامات خلوص',
                'excerpt'           => 'راهنمای انتخاب ژنراتور هوای خشک برای دستگاه‌های آنالیز FID، TOC و سیستم‌های پنوماتیک آزمایشگاهی.',
                'category'          => 'راهنمای خرید',
                'product_categories'=> '["gas-generators"]',
                'product_types'     => '["dry-air-gen"]',
                'author'            => 'مهندس نادری',
                'read_time'         => '۷ دقیقه',
                'published_at'      => '2024-04-29',
            ],
            [
                'slug'              => 'gas-detector-types-selection-guide',
                'title'             => 'انواع دتکتور گاز صنعتی: ثابت، پرتابل و چند گازی — راهنمای انتخاب جامع',
                'excerpt'           => 'بررسی فناوری‌های سنسور (کاتالیستی، الکتروشیمیایی، مادون قرمز) و معیارهای انتخاب دتکتور گاز مناسب.',
                'category'          => 'راهنمای خرید',
                'product_categories'=> '["gas-detectors"]',
                'product_types'     => '["toxic-detector","flammable-detector","multi-gas"]',
                'author'            => 'مهندس رضایی',
                'read_time'         => '۱۲ دقیقه',
                'published_at'      => '2024-05-01',
            ],
            [
                'slug'              => 'electromagnetic-flowmeter-water-industry',
                'title'             => 'فلومتر الکترومغناطیسی در صنعت آب و فاضلاب: انتخاب لاینر، الکترود و سایز مناسب',
                'excerpt'           => 'راهنمای تخصصی انتخاب فلومتر الکترومغناطیسی با تمرکز بر جنس لاینر، مواد الکترود و محاسبه سایز.',
                'category'          => 'مقاله تخصصی',
                'product_categories'=> '["flow-meters"]',
                'product_types'     => '["electromagnetic-flow"]',
                'author'            => 'مهندس محمدی',
                'read_time'         => '۱۰ دقیقه',
                'published_at'      => '2024-05-04',
            ],
            [
                'slug'              => 'mass-flow-controller-calibration',
                'title'             => 'فلوکنترلر جرمی (MFC): اصول عملکرد، کالیبراسیون و کاربرد در نیمه‌هادی و آزمایشگاه',
                'excerpt'           => 'بررسی اصول فلوکنترلر جرمی حرارتی و کوریولیس، نحوه کالیبراسیون و کاربردهای صنعتی و پژوهشی.',
                'category'          => 'مقاله تخصصی',
                'product_categories'=> '["flow-meters"]',
                'product_types'     => '["mass-flow-controller"]',
                'author'            => 'مهندس کریمی',
                'read_time'         => '۸ دقیقه',
                'published_at'      => '2024-05-07',
            ],
            [
                'slug'              => 'plc-cpu-siemens-rockwell-comparison',
                'title'             => 'ماژول CPU در PLC: مقایسه عملکرد Siemens S7-1500، S7-1200 و Rockwell CompactLogix',
                'excerpt'           => 'تحلیل سرعت پردازش، حافظه، پروتکل‌های ارتباطی و قابلیت‌های ایمنی ماژول‌های CPU پیشرفته.',
                'category'          => 'مقاله تخصصی',
                'product_categories'=> '["plc-equipment"]',
                'product_types'     => '["plc-cpu"]',
                'author'            => 'مهندس کریمی',
                'read_time'         => '۱۰ دقیقه',
                'published_at'      => '2024-05-09',
            ],
            [
                'slug'              => 'hmi-panel-selection-guide',
                'title'             => 'پنل HMI صنعتی: راهنمای انتخاب بر اساس سایز، رزولوشن و پروتکل ارتباطی',
                'excerpt'           => 'مقایسه پنل‌های HMI زیمنس (Comfort Panel)، راکول (PanelView) و اشنایدر (Magelis) برای پروژه‌های اتوماسیون.',
                'category'          => 'راهنمای خرید',
                'product_categories'=> '["plc-equipment"]',
                'product_types'     => '["hmi-panel"]',
                'author'            => 'مهندس احمدی',
                'read_time'         => '۸ دقیقه',
                'published_at'      => '2024-05-11',
            ],
            [
                'slug'              => 'plc-io-modules-analog-digital-safety',
                'title'             => 'ماژول ورودی/خروجی (I/O) در سیستم‌های PLC: آنالوگ، دیجیتال و ماژول‌های ایمنی',
                'excerpt'           => 'بررسی انواع ماژول‌های I/O، نحوه انتخاب بر اساس نوع سیگنال و الزامات ایمنی عملکردی SIL.',
                'category'          => 'مقاله تخصصی',
                'product_categories'=> '["plc-equipment"]',
                'product_types'     => '["plc-io"]',
                'author'            => 'مهندس رضایی',
                'read_time'         => '۹ دقیقه',
                'published_at'      => '2024-05-14',
            ],
            [
                'slug'              => 'rotary-vacuum-pump-guide',
                'title'             => 'پمپ خلاء روتاری: اصول عملکرد، انتخاب روغن و نگهداری پیشگیرانه',
                'excerpt'           => 'راهنمای جامع پمپ‌های خلاء روتاری تک‌مرحله و دو‌مرحله‌ای برای آزمایشگاه، خشک‌کن و سیستم‌های فیلتراسیون.',
                'category'          => 'مقاله تخصصی',
                'product_categories'=> '["lab-pumps"]',
                'product_types'     => '["vacuum-pump"]',
                'author'            => 'مهندس نادری',
                'read_time'         => '۸ دقیقه',
                'published_at'      => '2024-05-17',
            ],
            [
                'slug'              => 'peristaltic-pump-tubing-guide',
                'title'             => 'پمپ پریستالتیک: اصول عملکرد، انتخاب تیوب و کاربرد در انتقال دقیق سیالات',
                'excerpt'           => 'بررسی مکانیزم پریستالتیک، جنس تیوبینگ (سیلیکون، PharMed، Viton) و نرخ جریان قابل تنظیم.',
                'category'          => 'مقاله تخصصی',
                'product_categories'=> '["lab-pumps"]',
                'product_types'     => '["peristaltic-pump"]',
                'author'            => 'مهندس موسوی',
                'read_time'         => '۷ دقیقه',
                'published_at'      => '2024-05-19',
            ],
            [
                'slug'              => 'diaphragm-pump-lab-gas-sampling',
                'title'             => 'پمپ دیافراگمی آزمایشگاهی: مقایسه با پمپ خلاء و کاربرد در نمونه‌برداری گاز',
                'excerpt'           => 'تحلیل مزایای پمپ دیافراگمی KNF و مقایسه با پمپ‌های روتاری برای کاربردهای خشک و بدون روغن.',
                'category'          => 'راهنمای خرید',
                'product_categories'=> '["lab-pumps"]',
                'product_types'     => '["diaphragm-pump"]',
                'author'            => 'مهندس قاسمی',
                'read_time'         => '۶ دقیقه',
                'published_at'      => '2024-05-23',
            ],
        ];

        $inserted = 0;

        foreach ($posts as $post) {
            DB::table('blog_posts')->updateOrInsert(
                ['slug' => $post['slug']],
                [
                    'title'              => $post['title'],
                    'slug'               => $post['slug'],
                    'excerpt'            => $post['excerpt'],
                    'content'            => $post['excerpt'],
                    'author'             => $post['author'],
                    'category'           => $post['category'],
                    'product_categories' => $post['product_categories'],
                    'product_types'      => $post['product_types'],
                    'read_time'          => $post['read_time'],
                    'status'             => 'published',
                    'published_at'       => $post['published_at'],
                    'created_at'         => $now,
                    'updated_at'         => $now,
                ]
            );
            $inserted++;
        }

        $this->command->info("✅ {$inserted} مقاله با موفقیت وارد شد!");
    }
}
