<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

return new class extends Migration
{
    public function up(): void
    {
        if (! Schema::hasTable('store_settings')) {
            return;
        }

        $now = now();
        $definitions = [
            ['brand', 'brand.name', 'string', 'وینیمی بیکری', 'نام برند'],
            ['brand', 'brand.name_en', 'string', 'Winimi Bakery', 'نام انگلیسی برند'],
            ['brand', 'brand.tagline', 'string', 'کوکی، کیک و باکس هدیه', 'تگ‌لاین برند'],
            ['contact', 'contact.phone', 'string', '09212508746', 'شماره تماس'],
            ['contact', 'contact.email', 'string', 'hello@winimibakery.com', 'ایمیل پشتیبانی'],
            ['contact', 'contact.address', 'string', 'محدوده اندیشه، استان تهران', 'آدرس نمایشی'],
            ['contact', 'contact.city', 'string', 'اندیشه', 'شهر'],
            ['contact', 'contact.region', 'string', 'تهران', 'استان/منطقه'],
            ['contact', 'contact.whatsapp', 'string', '989212508746', 'شماره واتساپ'],
            ['contact', 'contact.telegram_url', 'string', '', 'لینک تلگرام'],
            ['contact', 'contact.telegram_enabled', 'boolean', '0', 'نمایش تلگرام'],
            ['contact', 'contact.instagram_url', 'string', 'https://www.instagram.com/winimi.bakery', 'لینک اینستاگرام'],
            ['contact', 'contact.instagram_handle', 'string', 'winimi.bakery', 'شناسه اینستاگرام'],
            ['contact', 'contact.map_url', 'string', 'https://maps.google.com/?q=Andisheh+Tehran', 'لینک نقشه'],
            ['contact', 'contact.working_hours_weekdays', 'string', 'پاسخ‌گویی با هماهنگی', 'ساعت پاسخ‌گویی روزهای کاری'],
            ['contact', 'contact.working_hours_weekends', 'string', 'پاسخ‌گویی با هماهنگی', 'ساعت پاسخ‌گویی آخر هفته'],
            ['navigation', 'navigation.header_1_label', 'string', 'خانه', 'منوی اصلی 1 - عنوان'],
            ['navigation', 'navigation.header_1_href', 'string', '/', 'منوی اصلی 1 - مسیر'],
            ['navigation', 'navigation.header_2_label', 'string', 'فروشگاه', 'منوی اصلی 2 - عنوان'],
            ['navigation', 'navigation.header_2_href', 'string', '/products', 'منوی اصلی 2 - مسیر'],
            ['navigation', 'navigation.header_3_label', 'string', 'هدیه', 'منوی اصلی 3 - عنوان'],
            ['navigation', 'navigation.header_3_href', 'string', '/gift', 'منوی اصلی 3 - مسیر'],
            ['navigation', 'navigation.header_4_label', 'string', 'راهنماها', 'منوی اصلی 4 - عنوان'],
            ['navigation', 'navigation.header_4_href', 'string', '/blog', 'منوی اصلی 4 - مسیر'],
            ['navigation', 'navigation.header_5_label', 'string', 'داستان ما', 'منوی اصلی 5 - عنوان'],
            ['navigation', 'navigation.header_5_href', 'string', '/about', 'منوی اصلی 5 - مسیر'],
            ['header', 'header.context_line', 'string', 'کوکی، کیک و هدیه؛ انتخاب بر اساس دسته و مناسبت', 'متن کوتاه زیر هدر'],
            ['header', 'header.mobile_subtitle', 'string', 'منوی سریع فروشگاه', 'زیرعنوان منوی موبایل'],
            ['header', 'header.mobile_guest_title', 'string', 'ورود به حساب', 'عنوان ورود کاربر مهمان'],
            ['header', 'header.mobile_guest_subtitle', 'string', 'سفارش‌ها، پروفایل و پیگیری', 'توضیح ورود کاربر مهمان'],
            ['header', 'header.categories_cta_label', 'string', 'انتخاب از دسته‌بندی‌ها', 'دکمه دسته‌بندی در منوی موبایل'],
            ['header', 'header.categories_cta_href', 'string', '/categories', 'مسیر دکمه دسته‌بندی'],
            ['header', 'header.whatsapp_label', 'string', 'واتساپ', 'برچسب واتساپ'],
            ['header', 'header.phone_label', 'string', 'تماس', 'برچسب تماس'],
            ['footer', 'footer.support_title', 'string', 'برای انتخاب بهتر، کنار شما هستیم', 'عنوان نوار پشتیبانی'],
            ['footer', 'footer.support_text', 'string', 'درباره محصول، تعداد مناسب یا شرایط سفارش سؤال داری؟ مستقیم با وینیمی صحبت کن.', 'متن نوار پشتیبانی'],
            ['footer', 'footer.phone_label', 'string', 'تماس', 'برچسب تماس فوتر'],
            ['footer', 'footer.whatsapp_label', 'string', 'واتساپ', 'برچسب واتساپ فوتر'],
            ['footer', 'footer.about_text', 'string', 'کوکی، کیک، دسر و باکس هدیه؛ با جزئیاتی که پیش از سفارش می‌بینی.', 'متن معرفی فوتر'],
            ['footer', 'footer.location_text', 'string', 'اندیشه، استان تهران', 'موقعیت نمایشی فوتر'],
            ['footer', 'footer.group_1_title', 'string', 'کشف وینیمی', 'عنوان گروه اول فوتر'],
            ['footer', 'footer.group_2_title', 'string', 'دسته‌بندی‌ها', 'عنوان گروه دسته‌بندی‌ها'],
            ['footer', 'footer.group_3_title', 'string', 'خدمات و راهنما', 'عنوان گروه خدمات'],
            ['footer', 'footer.legal_quality_label', 'string', 'سیاست شفافیت', 'عنوان لینک شفافیت'],
            ['footer', 'footer.legal_shipping_label', 'string', 'شرایط ارسال', 'عنوان لینک ارسال'],
            ['footer', 'footer.legal_privacy_label', 'string', 'حریم خصوصی', 'عنوان لینک حریم خصوصی'],
            ['footer', 'footer.legal_terms_label', 'string', 'شرایط استفاده', 'عنوان لینک شرایط استفاده'],
            ['footer', 'footer.developer_label', 'string', 'طراحی و توسعه توسط', 'متن معرفی توسعه‌دهنده'],
            ['footer', 'footer.developer_name', 'string', 'SHINETHREE', 'نام توسعه‌دهنده'],
            ['footer', 'footer.watermark', 'string', 'WINIMI BAKERY', 'واترمارک فوتر'],
            ['footer', 'footer.group_1_link_1_label', 'string', 'خانه', 'فوتر گروه 1 لینک 1 - عنوان'],
            ['footer', 'footer.group_1_link_1_href', 'string', '/', 'فوتر گروه 1 لینک 1 - مسیر'],
            ['footer', 'footer.group_1_link_2_label', 'string', 'همه محصولات', 'فوتر گروه 1 لینک 2 - عنوان'],
            ['footer', 'footer.group_1_link_2_href', 'string', '/products', 'فوتر گروه 1 لینک 2 - مسیر'],
            ['footer', 'footer.group_1_link_3_label', 'string', 'درباره ما', 'فوتر گروه 1 لینک 3 - عنوان'],
            ['footer', 'footer.group_1_link_3_href', 'string', '/about', 'فوتر گروه 1 لینک 3 - مسیر'],
            ['footer', 'footer.group_1_link_4_label', 'string', 'راهنماها', 'فوتر گروه 1 لینک 4 - عنوان'],
            ['footer', 'footer.group_1_link_4_href', 'string', '/blog', 'فوتر گروه 1 لینک 4 - مسیر'],
            ['footer', 'footer.group_1_link_5_label', 'string', 'تماس با ما', 'فوتر گروه 1 لینک 5 - عنوان'],
            ['footer', 'footer.group_1_link_5_href', 'string', '/contact', 'فوتر گروه 1 لینک 5 - مسیر'],
            ['footer', 'footer.group_3_link_1_label', 'string', 'مناطق ارسال', 'فوتر گروه 3 لینک 1 - عنوان'],
            ['footer', 'footer.group_3_link_1_href', 'string', '/locations', 'فوتر گروه 3 لینک 1 - مسیر'],
            ['footer', 'footer.group_3_link_2_label', 'string', 'سفارش سازمانی', 'فوتر گروه 3 لینک 2 - عنوان'],
            ['footer', 'footer.group_3_link_2_href', 'string', '/corporate', 'فوتر گروه 3 لینک 2 - مسیر'],
            ['footer', 'footer.group_3_link_3_label', 'string', 'راهنمای هدیه', 'فوتر گروه 3 لینک 3 - عنوان'],
            ['footer', 'footer.group_3_link_3_href', 'string', '/gift', 'فوتر گروه 3 لینک 3 - مسیر'],
            ['footer', 'footer.group_3_link_4_label', 'string', 'شرایط ارسال', 'فوتر گروه 3 لینک 4 - عنوان'],
            ['footer', 'footer.group_3_link_4_href', 'string', '/shipping', 'فوتر گروه 3 لینک 4 - مسیر'],
            ['footer', 'footer.group_3_link_5_label', 'string', 'سؤالات متداول', 'فوتر گروه 3 لینک 5 - عنوان'],
            ['footer', 'footer.group_3_link_5_href', 'string', '/faq', 'فوتر گروه 3 لینک 5 - مسیر'],
            ['home', 'home.meta_title', 'string', 'خرید کوکی، کیک و باکس هدیه', 'عنوان SEO صفحه اصلی'],
            ['home', 'home.meta_description', 'string', 'محصولات فعال وینیمی را براساس دسته یا مناسبت پیدا کنید؛ تصویر، قیمت، موجودی و شرایط هر انتخاب را ببینید و آنلاین سفارش دهید.', 'توضیح SEO صفحه اصلی'],
            ['home', 'home.hero_eyebrow', 'string', 'شیرینی دست‌ساز برای لحظه‌های شما', 'تیتر کوچک هیرو'],
            ['home', 'home.hero_title_line_1', 'string', 'طعم خوب برای', 'خط اول عنوان هیرو'],
            ['home', 'home.hero_title_line_2', 'string', 'هدیه، پذیرایی و حال خوب.', 'خط دوم عنوان هیرو'],
            ['home', 'home.hero_description', 'string', 'محصولات فعال وینیمی را براساس دسته یا مناسبت پیدا کن؛ تصویر، قیمت، موجودی و شرایط هر انتخاب را ببین و با خیال روشن‌تر سفارش بده.', 'توضیح هیرو'],
            ['home', 'home.hero_primary_label', 'string', 'مشاهده محصولات', 'دکمه اصلی هیرو'],
            ['home', 'home.hero_primary_href', 'string', '/products', 'مسیر دکمه اصلی هیرو'],
            ['home', 'home.hero_secondary_label', 'string', 'راهنمای انتخاب هدیه', 'دکمه دوم هیرو'],
            ['home', 'home.hero_secondary_href', 'string', '/gift', 'مسیر دکمه دوم هیرو'],
            ['home', 'home.hero_image_url', 'string', '', 'تصویر هیرو (URL؛ خالی = تصویر پیش‌فرض)'],
            ['home', 'home.hero_image_alt', 'string', 'کوکی شکلاتی تازه وینیمی', 'متن جایگزین تصویر هیرو'],
            ['home', 'home.hero_caption_label', 'string', 'انتخاب روشن، سفارش ساده', 'برچسب تصویر هیرو'],
            ['home', 'home.hero_caption_text', 'string', 'یک انتخاب شیرین، با جزئیاتی که پیش از سفارش می‌بینی.', 'متن تصویر هیرو'],
            ['home', 'home.categories_eyebrow', 'string', 'دسته‌های فعال فروشگاه', 'برچسب بخش دسته‌ها'],
            ['home', 'home.categories_title', 'string', 'دسته‌بندی محصولات وینیمی', 'عنوان بخش دسته‌ها'],
            ['home', 'home.categories_description', 'string', 'دسته موردنظرت را انتخاب کن و محصولات فعال، قیمت و جزئیات سفارش را ببین.', 'توضیح بخش دسته‌ها'],
            ['home', 'home.featured_eyebrow', 'string', 'انتخاب‌های پیشنهادی', 'برچسب محصولات پیشنهادی'],
            ['home', 'home.featured_title', 'string', 'چند انتخاب برای شروع', 'عنوان محصولات پیشنهادی'],
            ['home', 'home.featured_description', 'string', 'محصول، قیمت و موجودی را سریع مقایسه کن؛ برای انتخاب نوع یا دیدن جزئیات بیشتر، پیش‌نمایش را باز کن.', 'توضیح محصولات پیشنهادی'],
            ['home', 'home.featured_cta_label', 'string', 'مشاهده همه محصولات', 'دکمه محصولات پیشنهادی'],
            ['home', 'home.featured_cta_href', 'string', '/products', 'مسیر دکمه محصولات پیشنهادی'],
            ['home', 'home.occasion_eyebrow', 'string', 'انتخاب براساس موقعیت', 'برچسب بخش موقعیت'],
            ['home', 'home.occasion_title', 'string', 'برای چه لحظه‌ای انتخاب می‌کنی؟', 'عنوان بخش موقعیت'],
            ['home', 'home.occasion_description', 'string', 'به‌جای مرور همه‌چیز، از موقعیتت شروع کن؛ وینیمی مسیرهای مرتبط‌تر را جلو دستت می‌گذارد.', 'توضیح بخش موقعیت'],
            ['home', 'home.decision_eyebrow', 'string', 'کمک برای یک انتخاب روشن', 'برچسب بخش تصمیم'],
            ['home', 'home.decision_title', 'string', 'از نیازت شروع کن؛ مسیر مناسب را کوتاه‌تر برو', 'عنوان بخش تصمیم'],
            ['home', 'home.decision_description', 'string', 'اگر هنوز بین چند انتخاب مرددی، از یکی از مسیرهای زیر شروع کن. هر مسیر فقط اطلاعات مرتبط با همان تصمیم را جلو دستت می‌گذارد.', 'توضیح بخش تصمیم'],
            ['home', 'home.decision_faq_eyebrow', 'string', 'پرسش‌های پرتکرار', 'برچسب FAQ صفحه اصلی'],
            ['home', 'home.decision_faq_title', 'string', 'قبل از سفارش', 'عنوان FAQ صفحه اصلی'],
            ['home', 'home.editorial_eyebrow', 'string', 'یادداشت‌های کوتاه و کاربردی', 'برچسب راهنماهای صفحه اصلی'],
            ['home', 'home.editorial_title', 'string', 'قبل از انتخاب، کمی بیشتر بدان', 'عنوان راهنماهای صفحه اصلی'],
            ['home', 'home.editorial_description', 'string', 'چند دقیقه مطالعه برای انتخاب هدیه، پذیرایی و نگهداری بهتر محصولات.', 'توضیح راهنماهای صفحه اصلی'],
            ['home', 'home.editorial_cta_label', 'string', 'همه راهنماها', 'دکمه همه راهنماها'],
            ['home', 'home.editorial_cta_href', 'string', '/blog', 'مسیر همه راهنماها'],
            ['home', 'home.editorial_read_label', 'string', 'خواندن راهنما', 'برچسب خواندن راهنما'],
            ['home', 'home.marquee_1', 'string', 'کوکی‌های خانگی', 'مارکی صفحه اصلی 1'],
            ['home', 'home.marquee_2', 'string', 'مینی‌کوکی برای پذیرایی', 'مارکی صفحه اصلی 2'],
            ['home', 'home.marquee_3', 'string', 'کیک و چیزکیک', 'مارکی صفحه اصلی 3'],
            ['home', 'home.marquee_4', 'string', 'رول و کروسان', 'مارکی صفحه اصلی 4'],
            ['home', 'home.marquee_5', 'string', 'باکس هدیه', 'مارکی صفحه اصلی 5'],
            ['home', 'home.marquee_6', 'string', 'راهنمای انتخاب هدیه', 'مارکی صفحه اصلی 6'],
            ['home', 'home.marquee_7', 'string', 'سفارش سازمانی', 'مارکی صفحه اصلی 7'],
            ['home', 'home.marquee_8', 'string', 'پشتیبانی وینیمی', 'مارکی صفحه اصلی 8'],
            ['home', 'home.occasion_1_short_title', 'string', 'هدیه', 'موقعیت 1 - عنوان کوتاه'],
            ['home', 'home.occasion_1_eyebrow', 'string', 'برای یک انتخاب شخصی‌تر', 'موقعیت 1 - برچسب'],
            ['home', 'home.occasion_1_title', 'string', 'هدیه‌ای که از روی فکر انتخاب شده', 'موقعیت 1 - عنوان'],
            ['home', 'home.occasion_1_description', 'string', 'مناسبت، تعداد و سلیقه گیرنده را در نظر بگیر و از مسیر راهنمای هدیه به انتخاب روشن‌تری برس.', 'موقعیت 1 - توضیح'],
            ['home', 'home.occasion_1_action_label', 'string', 'رفتن به راهنمای هدیه', 'موقعیت 1 - دکمه'],
            ['home', 'home.occasion_1_href', 'string', '/gift', 'موقعیت 1 - مسیر'],
            ['home', 'home.occasion_1_image_url', 'string', '', 'موقعیت 1 - تصویر URL'],
            ['home', 'home.occasion_2_short_title', 'string', 'پذیرایی', 'موقعیت 2 - عنوان کوتاه'],
            ['home', 'home.occasion_2_eyebrow', 'string', 'برای جمع‌های کوچک و بزرگ', 'موقعیت 2 - برچسب'],
            ['home', 'home.occasion_2_title', 'string', 'پذیرایی خوش‌ریتم، بدون انتخاب اضافه', 'موقعیت 2 - عنوان'],
            ['home', 'home.occasion_2_description', 'string', 'تعداد مهمان‌ها و حال‌وهوای دورهمی را مشخص کن و گزینه‌های جمع‌وجور و قابل مقایسه را ببین.', 'موقعیت 2 - توضیح'],
            ['home', 'home.occasion_2_action_label', 'string', 'دیدن گزینه‌های پذیرایی', 'موقعیت 2 - دکمه'],
            ['home', 'home.occasion_2_href', 'string', '/products/category/mini-cookies', 'موقعیت 2 - مسیر'],
            ['home', 'home.occasion_2_image_url', 'string', '', 'موقعیت 2 - تصویر URL'],
            ['home', 'home.occasion_3_short_title', 'string', 'روزمره', 'موقعیت 3 - عنوان کوتاه'],
            ['home', 'home.occasion_3_eyebrow', 'string', 'برای چای، قهوه و حال خوب', 'موقعیت 3 - برچسب'],
            ['home', 'home.occasion_3_title', 'string', 'یک شیرینی کوچک برای همین امروز', 'موقعیت 3 - عنوان'],
            ['home', 'home.occasion_3_description', 'string', 'میان کوکی‌های فعال، طعم و بافتی را پیدا کن که به حال‌وهوای امروزت نزدیک‌تر است.', 'موقعیت 3 - توضیح'],
            ['home', 'home.occasion_3_action_label', 'string', 'دیدن کوکی‌ها', 'موقعیت 3 - دکمه'],
            ['home', 'home.occasion_3_href', 'string', '/products/category/cookies', 'موقعیت 3 - مسیر'],
            ['home', 'home.occasion_3_image_url', 'string', '', 'موقعیت 3 - تصویر URL'],
            ['home', 'home.decision_path_1_eyebrow', 'string', 'شروع از نوع محصول', 'مسیر تصمیم 1 - برچسب'],
            ['home', 'home.decision_path_1_title', 'string', 'دسته‌بندی‌های فروشگاه', 'مسیر تصمیم 1 - عنوان'],
            ['home', 'home.decision_path_1_description', 'string', 'محصولات مشابه را کنار هم ببین و سریع‌تر مقایسه کن.', 'مسیر تصمیم 1 - توضیح'],
            ['home', 'home.decision_path_1_href', 'string', '/products', 'مسیر تصمیم 1 - مسیر'],
            ['home', 'home.decision_path_1_action_label', 'string', 'مشاهده دسته‌ها', 'مسیر تصمیم 1 - دکمه'],
            ['home', 'home.decision_path_2_eyebrow', 'string', 'شروع از مناسبت', 'مسیر تصمیم 2 - برچسب'],
            ['home', 'home.decision_path_2_title', 'string', 'راهنمای انتخاب هدیه', 'مسیر تصمیم 2 - عنوان'],
            ['home', 'home.decision_path_2_description', 'string', 'برای مناسبت، تعداد و سلیقه گیرنده مسیر مناسب‌تری پیدا کن.', 'مسیر تصمیم 2 - توضیح'],
            ['home', 'home.decision_path_2_href', 'string', '/gift', 'مسیر تصمیم 2 - مسیر'],
            ['home', 'home.decision_path_2_action_label', 'string', 'رفتن به راهنما', 'مسیر تصمیم 2 - دکمه'],
            ['home', 'home.decision_path_3_eyebrow', 'string', 'پیش از سفارش', 'مسیر تصمیم 3 - برچسب'],
            ['home', 'home.decision_path_3_title', 'string', 'راهنماهای کوتاه وینیمی', 'مسیر تصمیم 3 - عنوان'],
            ['home', 'home.decision_path_3_description', 'string', 'درباره تعداد، نگهداری و انتخاب بهتر بیشتر بدان.', 'مسیر تصمیم 3 - توضیح'],
            ['home', 'home.decision_path_3_href', 'string', '/blog', 'مسیر تصمیم 3 - مسیر'],
            ['home', 'home.decision_path_3_action_label', 'string', 'خواندن راهنماها', 'مسیر تصمیم 3 - دکمه'],
            ['home', 'home.editorial_1_slug', 'string', 'choose-food-gift-box', 'اسلاگ راهنمای صفحه اصلی 1'],
            ['home', 'home.editorial_2_slug', 'string', 'cookie-storage-guide', 'اسلاگ راهنمای صفحه اصلی 2'],
            ['home', 'home.editorial_3_slug', 'string', 'cookies-per-guest-guide', 'اسلاگ راهنمای صفحه اصلی 3'],
            ['gift', 'gift.meta_title', 'string', 'باکس هدیه کوکی و شیرینی', 'عنوان SEO هدیه'],
            ['gift', 'gift.meta_description', 'string', 'مشاهده محصولات هدیه و ثبت درخواست اختصاصی هدیه در وینیمی.', 'توضیح SEO هدیه'],
            ['gift', 'gift.hero_badge', 'string', 'محصولات و درخواست هدیه', 'برچسب هیرو هدیه'],
            ['gift', 'gift.hero_title', 'string', 'هدیه‌ای متناسب با مناسبت شما', 'عنوان هیرو هدیه'],
            ['gift', 'gift.hero_description', 'string', 'محصولات آماده را از فروشگاه انتخاب کنید. برای کارت، بسته‌بندی یا ترکیب اختصاصی، درخواست ثبت کنید تا امکان اجرا، هزینه و زمان آماده‌سازی بررسی شود.', 'توضیح هیرو هدیه'],
            ['gift', 'gift.hero_primary_label', 'string', 'مشاهده محصولات هدیه', 'دکمه اصلی هدیه'],
            ['gift', 'gift.hero_primary_href', 'string', '/products', 'مسیر دکمه اصلی هدیه'],
            ['gift', 'gift.hero_support_label', 'string', 'مشاوره پشتیبانی', 'برچسب مشاوره هدیه'],
            ['gift', 'gift.hero_image_url', 'string', '', 'تصویر هیرو هدیه (URL؛ خالی = پیش‌فرض)'],
            ['gift', 'gift.hero_image_alt', 'string', 'تصویر نمایشی بسته‌بندی هدیه وینیمی', 'متن جایگزین تصویر هدیه'],
            ['gift', 'gift.occasions_title', 'string', 'برای مناسبت‌های مختلف', 'عنوان مناسبت‌های هدیه'],
            ['gift', 'gift.products_title', 'string', 'محصولات هدیه فعال', 'عنوان محصولات هدیه'],
            ['gift', 'gift.inquiry_title', 'string', 'ثبت درخواست هدیه اختصاصی', 'عنوان فرم هدیه'],
            ['gift', 'gift.inquiry_description', 'string', 'مناسبت، تعداد، بودجه تقریبی، شهر مقصد و تاریخ موردنظر را بنویسید. ثبت فرم به معنی تأیید قطعی ظرفیت یا قیمت نیست.', 'توضیح فرم هدیه'],
            ['gift', 'gift.inquiry_subject', 'string', 'درخواست هدیه اختصاصی', 'موضوع پیش‌فرض فرم هدیه'],
            ['gift', 'gift.inquiry_message_label', 'string', 'جزئیات مناسبت و درخواست', 'برچسب پیام فرم هدیه'],
            ['gift', 'gift.occasion_1_title', 'string', 'سالگرد و مناسبت شخصی', 'هدیه مناسبت 1 - عنوان'],
            ['gift', 'gift.occasion_1_description', 'string', 'درخواست کارت و ترکیب پیشنهادی', 'هدیه مناسبت 1 - توضیح'],
            ['gift', 'gift.occasion_2_title', 'string', 'تولد و جشن', 'هدیه مناسبت 2 - عنوان'],
            ['gift', 'gift.occasion_2_description', 'string', 'انتخاب محصول و تعداد متناسب با جشن', 'هدیه مناسبت 2 - توضیح'],
            ['gift', 'gift.occasion_3_title', 'string', 'تشکر و تبریک', 'هدیه مناسبت 3 - عنوان'],
            ['gift', 'gift.occasion_3_description', 'string', 'درخواست بسته‌بندی هدیه پس از استعلام', 'هدیه مناسبت 3 - توضیح'],
            ['gift', 'gift.occasion_4_title', 'string', 'هدیه خانوادگی', 'هدیه مناسبت 4 - عنوان'],
            ['gift', 'gift.occasion_4_description', 'string', 'ترکیب محصولات موجود فروشگاه', 'هدیه مناسبت 4 - توضیح'],
            ['corporate', 'corporate.meta_title', 'string', 'استعلام سفارش شرکتی و سازمانی', 'عنوان SEO سازمانی'],
            ['corporate', 'corporate.meta_description', 'string', 'ثبت و پیگیری درخواست سفارش سازمانی وینیمی از طریق بک‌اند فروشگاه.', 'توضیح SEO سازمانی'],
            ['corporate', 'corporate.hero_title', 'string', 'استعلام هدیه و پذیرایی سازمانی', 'عنوان هیرو سازمانی'],
            ['corporate', 'corporate.hero_description', 'string', 'محصول، تعداد، بودجه، تاریخ و مقصد را در فرم ثبت کنید تا قابلیت اجرا و شرایط نهایی در پنل فروشگاه بررسی شود.', 'توضیح هیرو سازمانی'],
            ['corporate', 'corporate.hero_warning', 'string', 'چاپ لوگو، تخفیف حجمی، نوع فاکتور و همکاری دوره‌ای فقط پس از تأیید کتبی جزئیات معتبر هستند.', 'هشدار هیرو سازمانی'],
            ['corporate', 'corporate.support_label', 'string', 'سؤال از پشتیبانی', 'برچسب پشتیبانی سازمانی'],
            ['corporate', 'corporate.use_cases_title', 'string', 'موارد قابل بررسی', 'عنوان موارد قابل بررسی'],
            ['corporate', 'corporate.inquiry_title', 'string', 'ثبت درخواست سازمانی', 'عنوان فرم سازمانی'],
            ['corporate', 'corporate.inquiry_description', 'string', 'نام مجموعه، محصول یا نوع پذیرایی، تعداد، تاریخ تحویل، شهر مقصد و نیاز مربوط به فاکتور یا بسته‌بندی را ثبت کنید.', 'توضیح فرم سازمانی'],
            ['corporate', 'corporate.inquiry_subject', 'string', 'استعلام سفارش سازمانی', 'موضوع فرم سازمانی'],
            ['corporate', 'corporate.inquiry_message_label', 'string', 'جزئیات سفارش یا همکاری', 'برچسب پیام فرم سازمانی'],
            ['corporate', 'corporate.request_1_title', 'string', 'بسته‌بندی و شخصی‌سازی', 'کارت سازمانی 1 - عنوان'],
            ['corporate', 'corporate.request_1_description', 'string', 'نوع جعبه، کارت، روبان یا درج لوگو براساس تعداد و زمان استعلام می‌شود.', 'کارت سازمانی 1 - توضیح'],
            ['corporate', 'corporate.request_2_title', 'string', 'قیمت سفارش تعداد بالا', 'کارت سازمانی 2 - عنوان'],
            ['corporate', 'corporate.request_2_description', 'string', 'قیمت بعد از مشخص‌شدن محصول، تعداد، تاریخ و مقصد محاسبه می‌شود.', 'کارت سازمانی 2 - توضیح'],
            ['corporate', 'corporate.request_3_title', 'string', 'پیش‌فاکتور و نوع فاکتور', 'کارت سازمانی 3 - عنوان'],
            ['corporate', 'corporate.request_3_description', 'string', 'امکان ارائه نوع فاکتور موردنیاز پیش از تأیید سفارش بررسی می‌شود.', 'کارت سازمانی 3 - توضیح'],
            ['corporate', 'corporate.request_4_title', 'string', 'همکاری دوره‌ای', 'کارت سازمانی 4 - عنوان'],
            ['corporate', 'corporate.request_4_description', 'string', 'ظرفیت تولید، بازه تحویل و شرایط همکاری برای هر درخواست جداگانه ارزیابی می‌شود.', 'کارت سازمانی 4 - توضیح'],
            ['corporate', 'corporate.use_case_1', 'string', 'پذیرایی جلسه یا رویداد', 'مورد سازمانی 1'],
            ['corporate', 'corporate.use_case_2', 'string', 'هدیه کارکنان یا مشتریان', 'مورد سازمانی 2'],
            ['corporate', 'corporate.use_case_3', 'string', 'پک خوشامدگویی', 'مورد سازمانی 3'],
            ['corporate', 'corporate.use_case_4', 'string', 'سفارش مناسبتی تعداد بالا', 'مورد سازمانی 4'],
            ['corporate', 'corporate.use_case_5', 'string', 'درخواست همکاری کافه یا مجموعه پذیرایی', 'مورد سازمانی 5'],
        ];

        foreach ($definitions as [$group, $key, $type, $value, $label]) {
            DB::table('store_settings')->insertOrIgnore([
                'group' => $group,
                'key' => $key,
                'type' => $type,
                'value' => $value,
                'label' => $label,
                'is_public' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        if (
            Schema::hasTable('bakery_faqs')
            && ! DB::table('bakery_faqs')->where('category', 'home-decision')->exists()
        ) {
            DB::table('bakery_faqs')->insert([
                [
                    'public_id' => (string) Str::ulid(),
                    'category' => 'home-decision',
                    'question' => 'از کجا محصول مناسب را پیدا کنم؟',
                    'answer' => 'اگر نوع محصول را می‌دانی، از دسته‌بندی‌ها شروع کن. برای هدیه یا پذیرایی هم مسیرهای پیشنهادی، گزینه‌های مرتبط را کوتاه‌تر و روشن‌تر نشان می‌دهند.',
                    'sort_order' => 10,
                    'is_active' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'public_id' => (string) Str::ulid(),
                    'category' => 'home-decision',
                    'question' => 'قیمت و موجودی هر محصول کجا نمایش داده می‌شود؟',
                    'answer' => 'قیمت، وضعیت موجودی و انتخاب‌های قابل سفارش در کارت و صفحه همان محصول نمایش داده می‌شوند و اطلاعات نهایی پیش از ثبت سفارش دوباره قابل بررسی است.',
                    'sort_order' => 20,
                    'is_active' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'public_id' => (string) Str::ulid(),
                    'category' => 'home-decision',
                    'question' => 'روش تحویل چه زمانی مشخص می‌شود؟',
                    'answer' => 'روش‌های قابل انتخاب با توجه به مقصد و شرایط نگهداری محصول در مسیر سفارش نمایش داده می‌شوند؛ محصولات نیازمند سرمایش نیز نشان مشخص دارند.',
                    'sort_order' => 30,
                    'is_active' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'public_id' => (string) Str::ulid(),
                    'category' => 'home-decision',
                    'question' => 'پیش از پرداخت چه اطلاعاتی می‌بینم؟',
                    'answer' => 'محصولات سبد، تعداد، مقصد، روش تحویل و مبلغ نهایی پیش از ورود به درگاه نمایش داده می‌شوند تا بتوانی سفارش را یک‌بار کامل بررسی کنی.',
                    'sort_order' => 40,
                    'is_active' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            ]);
        }
    }

    public function down(): void
    {
        if (Schema::hasTable('store_settings')) {
            DB::table('store_settings')
                ->whereIn('key', [
                    'brand.name', 'brand.name_en', 'brand.tagline',
                    'contact.phone', 'contact.email', 'contact.address', 'contact.city', 'contact.region', 'contact.whatsapp', 'contact.telegram_url', 'contact.telegram_enabled', 'contact.instagram_url', 'contact.instagram_handle', 'contact.map_url', 'contact.working_hours_weekdays', 'contact.working_hours_weekends',
                    'navigation.header_1_label', 'navigation.header_1_href', 'navigation.header_2_label', 'navigation.header_2_href', 'navigation.header_3_label', 'navigation.header_3_href', 'navigation.header_4_label', 'navigation.header_4_href', 'navigation.header_5_label', 'navigation.header_5_href',
                    'header.context_line', 'header.mobile_subtitle', 'header.mobile_guest_title', 'header.mobile_guest_subtitle', 'header.categories_cta_label', 'header.categories_cta_href', 'header.whatsapp_label', 'header.phone_label',
                    'footer.support_title', 'footer.support_text', 'footer.phone_label', 'footer.whatsapp_label', 'footer.about_text', 'footer.location_text', 'footer.group_1_title', 'footer.group_2_title', 'footer.group_3_title', 'footer.legal_quality_label', 'footer.legal_shipping_label', 'footer.legal_privacy_label', 'footer.legal_terms_label', 'footer.developer_label', 'footer.developer_name', 'footer.watermark',
                    'footer.group_1_link_1_label', 'footer.group_1_link_1_href', 'footer.group_1_link_2_label', 'footer.group_1_link_2_href', 'footer.group_1_link_3_label', 'footer.group_1_link_3_href', 'footer.group_1_link_4_label', 'footer.group_1_link_4_href', 'footer.group_1_link_5_label', 'footer.group_1_link_5_href',
                    'footer.group_3_link_1_label', 'footer.group_3_link_1_href', 'footer.group_3_link_2_label', 'footer.group_3_link_2_href', 'footer.group_3_link_3_label', 'footer.group_3_link_3_href', 'footer.group_3_link_4_label', 'footer.group_3_link_4_href', 'footer.group_3_link_5_label', 'footer.group_3_link_5_href',
                    'home.meta_title', 'home.meta_description', 'home.hero_eyebrow', 'home.hero_title_line_1', 'home.hero_title_line_2', 'home.hero_description', 'home.hero_primary_label', 'home.hero_primary_href', 'home.hero_secondary_label', 'home.hero_secondary_href', 'home.hero_image_url', 'home.hero_image_alt', 'home.hero_caption_label', 'home.hero_caption_text', 'home.categories_eyebrow', 'home.categories_title', 'home.categories_description', 'home.featured_eyebrow', 'home.featured_title', 'home.featured_description', 'home.featured_cta_label', 'home.featured_cta_href', 'home.occasion_eyebrow', 'home.occasion_title', 'home.occasion_description', 'home.decision_eyebrow', 'home.decision_title', 'home.decision_description', 'home.decision_faq_eyebrow', 'home.decision_faq_title', 'home.editorial_eyebrow', 'home.editorial_title', 'home.editorial_description', 'home.editorial_cta_label', 'home.editorial_cta_href', 'home.editorial_read_label',
                    'home.marquee_1', 'home.marquee_2', 'home.marquee_3', 'home.marquee_4', 'home.marquee_5', 'home.marquee_6', 'home.marquee_7', 'home.marquee_8',
                    'home.occasion_1_short_title', 'home.occasion_1_eyebrow', 'home.occasion_1_title', 'home.occasion_1_description', 'home.occasion_1_action_label', 'home.occasion_1_href', 'home.occasion_1_image_url', 'home.occasion_2_short_title', 'home.occasion_2_eyebrow', 'home.occasion_2_title', 'home.occasion_2_description', 'home.occasion_2_action_label', 'home.occasion_2_href', 'home.occasion_2_image_url', 'home.occasion_3_short_title', 'home.occasion_3_eyebrow', 'home.occasion_3_title', 'home.occasion_3_description', 'home.occasion_3_action_label', 'home.occasion_3_href', 'home.occasion_3_image_url',
                    'home.decision_path_1_eyebrow', 'home.decision_path_1_title', 'home.decision_path_1_description', 'home.decision_path_1_href', 'home.decision_path_1_action_label', 'home.decision_path_2_eyebrow', 'home.decision_path_2_title', 'home.decision_path_2_description', 'home.decision_path_2_href', 'home.decision_path_2_action_label', 'home.decision_path_3_eyebrow', 'home.decision_path_3_title', 'home.decision_path_3_description', 'home.decision_path_3_href', 'home.decision_path_3_action_label', 'home.editorial_1_slug', 'home.editorial_2_slug', 'home.editorial_3_slug',
                    'gift.meta_title', 'gift.meta_description', 'gift.hero_badge', 'gift.hero_title', 'gift.hero_description', 'gift.hero_primary_label', 'gift.hero_primary_href', 'gift.hero_support_label', 'gift.hero_image_url', 'gift.hero_image_alt', 'gift.occasions_title', 'gift.products_title', 'gift.inquiry_title', 'gift.inquiry_description', 'gift.inquiry_subject', 'gift.inquiry_message_label', 'gift.occasion_1_title', 'gift.occasion_1_description', 'gift.occasion_2_title', 'gift.occasion_2_description', 'gift.occasion_3_title', 'gift.occasion_3_description', 'gift.occasion_4_title', 'gift.occasion_4_description',
                    'corporate.meta_title', 'corporate.meta_description', 'corporate.hero_title', 'corporate.hero_description', 'corporate.hero_warning', 'corporate.support_label', 'corporate.use_cases_title', 'corporate.inquiry_title', 'corporate.inquiry_description', 'corporate.inquiry_subject', 'corporate.inquiry_message_label', 'corporate.request_1_title', 'corporate.request_1_description', 'corporate.request_2_title', 'corporate.request_2_description', 'corporate.request_3_title', 'corporate.request_3_description', 'corporate.request_4_title', 'corporate.request_4_description', 'corporate.use_case_1', 'corporate.use_case_2', 'corporate.use_case_3', 'corporate.use_case_4', 'corporate.use_case_5',
                ])
                ->delete();
        }

        if (Schema::hasTable('bakery_faqs')) {
            DB::table('bakery_faqs')->where('category', 'home-decision')->delete();
        }
    }
};
